services:
  namenode:
    image: apache/hadoop:3.4.1
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      CORE-SITE.XML_fs.default.name: "hdfs://namenode:8020"
      CORE-SITE.XML_fs.defaultFS: "hdfs://namenode:8020"
      HDFS-SITE.XML_dfs.namenode.rpc-address: "namenode:8020"
      HDFS-SITE.XML_dfs.replication: "1"
    networks:
      - spark-network

  datanode:
    image: apache/hadoop:3.4.1
    hostname: datanode
    command: ["hdfs", "datanode"]
    ports:
      - 9864:9864
    environment:
      HADOOP_HOME: /opt/hadoop
      CORE-SITE.XML_fs.default.name: "hdfs://namenode:8020"
      CORE-SITE.XML_fs.defaultFS: "hdfs://namenode:8020"
      HDFS-SITE.XML_dfs.datanode.data.dir: "/tmp/hadoop-root/dfs/data"
      HDFS-SITE.XML_dfs.replication: "1"
    depends_on:
      - namenode
    networks:
      - spark-network

  spark-master:
    image: apache/spark:3.5.3-python3
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080" # Changed from 8080:8080 to 9090:8080
      - "7077:7077"
      - "4040:4040"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - ./spark_apps:/opt/spark-apps
      - ./spark_data:/opt/spark-data
    depends_on:
      - namenode
      - datanode
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:3.5.3-python3
    container_name: spark-worker-1
    hostname: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
      - ./spark_apps:/opt/spark-apps
      - ./spark_data:/opt/spark-data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
